Pepperi-Addons/papi-sdk

- endpoint.ts
- entities/fileStorage.ts
- entities/index.ts
- index.ts
- package-lock.json
- package.json
- papi-client.ts
Changed FindById to get,
Added minor version
> Add filestorage endpoint

- entities/codeJobs.ts
- package-lock.json
- package.json
- papi-client.ts
Added missing properties on Code Job Object
Added 'X-Pepperi-OwnerID' in case constructor get parameter name AddonUUID
> Roi branch

- endpoint.ts
- endpoints/meta-data.ts
- package-lock.json
- package.json
- papi-client.ts
This is needed for my and Yonis tests
> Adding delete and edited how delete works

- entities/api-field-object.ts
- package-lock.json
- package.json
Tested locally, needed to create tests of Fields
> Small fix in the object of Field

- endpoint.ts
- endpoints/maintenance.ts
- entities/export.ts
- entities/index.ts
- entities/maintenance.ts
- package-lock.json
- package.json
added export function to endpoint base class
> Add export function

- endpoints/meta-data.ts
- entities/api-field-object.ts
- entities/user-defined-tables.ts
- package-lock.json
- package.json
Add include_owned option to GET endpoint of fields
> Added include owned option to get fields

- entities/atd-meta-data.ts
- entities/user-defined-tables.ts
- package-lock.json
- package.json
The changes:
UDT
1. removed owner from body
2. CreationDate changed to  CreationDateTime
3. ModificationDate changed to  ModificationDateTime
ATD
1. removed owner from body
2. CreationDate changed to  CreationDateTime
3. ModificationDate changed to  ModificationDateTime
4. added InternalID (in addition to TypeID)
5. POST is new - the mandatory fields: ExternalID & Description
> Update the changed objects for Oren

- endpoint.ts
- endpoints/addons.ts
- entities/addons.ts
- package-lock.json
- package.json
- papi-client.ts
added ADAL endpoint. following changes was made:
1. add 2 interfaces on addon entity file
2. add AddonData class to handle all endpoint logic
3. add 2 optional parameters in papi client constructor
* AddonSecretKey - will be mapped to 'X-Pepperi-SecretKey' header if exist
* ActionUUID - will be mapped to 'X-Pepperi-ActionUUID' header if exist
> Adal endpoints

- endpoint.ts
- package-lock.json
- package.json
@Chasky-H please see if it can be merged, feel free to fix, but let me know.
> Added async count to Endpoint

- entities/contact.ts
- entities/index.ts
- package-lock.json
- package.json
- papi-client.ts
> Contact endpoint

- endpoints/meta-data.ts
- entities/atd-settings.ts
- package-lock.json
- package.json
1. fix ATDSettings entity - the IDs ate number and not string 
2. add "Include_internal" flag to GET Fields endpoint
> fix Atd settings entity and add `include_internal`

- endpoints/generic-resource.ts
- endpoints/index.ts
- entities/generic-resource.ts
- entities/index.ts
- package-lock.json
- package.json
- papi-client.ts
adding generic resource endpoints to papi sdk
> Di 20577 generic resource

- entities/addons.ts
- entities/user_defined_collections.ts
- package-lock.json
- package.json
Adding missing properties and field's types
> Add field types

- endpoints/generic-resource.ts
- entities/addons.ts
- entities/user_defined_collections.ts
- package-lock.json
- package.json
* Add mandatory property to Collection Field type
* fix options init on find method of generic resource
> minor issues

- entities/addons.ts
- entities/generic-resource.ts
- entities/user_defined_collections.ts
- package-lock.json
- package.json
Added unique property to SchemeField type
> Add unique fields

- entities/addons.ts
- package-lock.json
- package.json
added 'papi' & 'contained' scheme types
removed 'cpi_meta_data'
> Scheme changes

- entities/addons.ts
- package-lock.json
- package.json
[API design PR](https://app.gitbook.com/o/-LUP1oYCM4aw4IDpwJDW/s/-LVCwP9BVdmHIds0xwia/~/changes/1713/pepperi-resource-schema).
Note: version is higher than [Crawler PR](https://github.com/Pepperi-Addons/papi-sdk/pull/195)
> Di 23398 sync records

- endpoints/addons.ts
- endpoints/crawler.ts
- entities/crawler/crawler-input.ts
- entities/crawler/multi-crawler-input.ts
- entities/crawler/multi-crawler-output.ts
- entities/index.ts
- package-lock.json
- package.json
Added `LockID` to `MultiCrawlerInput`.
Added `CrawlersStatus` to `MultiCrawlerOutput`.
Created a new endpoint `MultiCrawlerEndpoint` in the same file as `CrawlerEndpoint`.
Exposed `multi_crawl` via `addons`.
And some minor import changes.
> Multi Crawler - API update

- endpoints/addons.ts
- entities/distinct-values.ts
- entities/index.ts
- package-lock.json
- package.json
Merge only after https://github.com/Pepperi-Addons/AddonInfaSDK/pull/54
> Add distinct values endpoints

- endpoints/addons.ts
- entities/index.ts
- entities/nebulus.ts
- package-lock.json
- package.json
[mapping PR](https://github.com/Pepperi-Addons/AddonInfaSDK/pull/66)
> Publish Sync Rules API (Nebulus Rebuild)

- entities/addons.ts
- package-lock.json
- package.json
Should be merged after [API design PR](https://app.gitbook.com/o/-LUP1oYCM4aw4IDpwJDW/s/-LVCwP9BVdmHIds0xwia/~/changes/1781/pepperi-resource-schema).
> Sync Rules

- endpoints/addons.ts
- endpoints/crawler.ts
- package-lock.json
- package.json
Note to future self: use newly released version on UDC & Nebulus.
> Nebulus Crawler Callback

- entities/addons.ts
- entities/graph-sync-cache.ts
- entities/index.ts
- entities/profile.ts
- package-lock.json
- package.json
Extracted `PathData` from `AddonDataScheme`.
Added cache configurations, labels and edges.
Added `Key` to profile.
> Edges Support

- entities/graph-sync-cache.ts
- entities/sync-cache.ts
- package-lock.json
- package.json
> Graph Cache Interfaces

- entities/sync-cache.ts
- package-lock.json
- package.json
Updated based on [API design](https://apidesign.pepperi.com/sync/open-sync/cache-interface#upsert-scheme).
There is a [PR on API design](https://app.gitbook.com/o/-LUP1oYCM4aw4IDpwJDW/s/-LVCwP9BVdmHIds0xwia/~/changes/1829/sync/open-sync/cache-interface#purge-a-scheme-from-a-source) too.
> Update Cache Scheme

- entities/sync-cache.ts
- package-lock.json
- package.json
`ModificationDateTimeFieldID` -> `ModificationFieldID`
> Update Cache Scheme 2

- endpoints/graph-cache.ts
- endpoints/index.ts
- entities/graph-sync-cache.ts
- entities/sync-cache.ts
- package-lock.json
- package.json
- papi-client.ts
Added ido4j types & endpoints in papi root.
---
> Graph Cache Endpoints

- entities/graph-sync-cache.ts
- package-lock.json
- package.json
`InternalID` -> `ProfileID`
---
---
> Cache Configuration Fix
